name: 'Deploy Plugin'

on:
  workflow_call:
    inputs:

      zip_files:
        description: 'Files and directories to include in the zip'
        required: false
        type: string
        default: 'includes vendor *.php *.txt'

      version:
        description: 'Version to deploy'
        required: true
        type: string
      
      fail_on_duplicate:
        description: 'Whether to fail on duplicate plugin versions'
        type: boolean
        required: false
        default: true

      overwrite:
        description: 'Whether to overwrite existing plugin versions'
        type: boolean
        required: false
        default: false
        
      plugin_slug:
        description: 'The slug of the plugin on WordPress.org and Freemius'
        required: true
        type: string
        
      plugin_id:
        description: 'Freemius plugin ID'
        required: true
        type: string
        
      deploy_to_wp:
        description: 'Whether to deploy to WordPress.org or not'
        type: boolean
        required: true

      update_feed_item_key:
        description: 'The key for the update feed item'
        required: true
        type: string
        
    secrets:
      FREEMIUS_PUBLIC_KEY:
        required: true
        
      DEV_ID:
        required: true
        
      FREEMIUS_SECRET_KEY:
        required: true
        
      WP_SVN_USERNAME:
        required: false
    
      WP_SVN_PASSWORD:
        required: false

      BLD_API_KEY:
        required: true

      UPDATE_FEED_URL:
        required: true

      SSH_PRIVATE_KEY_GRAVITYOPS_CORE:
        required: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # Checkout the repository
      - name: Checkout
        uses: actions/checkout@v4

      # Setup PHP
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.0'
          tools: composer

      - name: Setup SSH Agent
        uses: webfactory/ssh-agent@v0.8.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY_GRAVITYOPS_CORE }}

      - name: Install Production Dependencies
        run: |
          composer config repositories.gravityops-local --unset
          composer config require-dev.gravityops/core --unset
          composer config minimum-stability stable
          composer config prefer-stable true
            
          # Extract version dynamically from composer.json
          CORE_VERSION=$(jq -r '.require["gravityops/core"]' composer.json)
            
          # Install all dependencies while forcing the @stable tag for core
          composer require "gravityops/core:${CORE_VERSION}@stable" --no-dev --no-progress --optimize-autoloader --no-interaction

      - name: Prefix namespaces (Strauss)
        run: composer run-script prefix-namespaces

      # Create Zip
      - name: Create Zip
        run: |
          mkdir -p build
          zip -r build/plugin.zip ${{ inputs.zip_files }}

      # Deploy to Freemius
      - name: Deploy to Freemius
        id: freemius_deploy
        uses: eitan-brightleaf/freemius-deploy@main
        with:
          file_name: build/plugin.zip
          release_mode: 'released'
          add_contributor: 'true'
          fail_on_duplicate: '${{ inputs.fail_on_duplicate }}'
          overwrite: '${{ inputs.overwrite }}'
          download_premium: 'false'
          download_free: ${{ inputs.deploy_to_wp }}
        env:
          PUBLIC_KEY: ${{ secrets.FREEMIUS_PUBLIC_KEY }}
          DEV_ID: ${{ secrets.DEV_ID }}
          SECRET_KEY: ${{ secrets.FREEMIUS_SECRET_KEY }}
          PLUGIN_SLUG: ${{ inputs.plugin_slug }}
          PLUGIN_ID: ${{ inputs.plugin_id }}

      - name: Unzip plugin for WP.org
        if: ${{ inputs.deploy_to_wp }}
        run: |
          mkdir plugin-dir
          unzip ${{ steps.freemius_deploy.outputs.free_version }} -d plugin-dir
          if [ -d "plugin-dir/${{ inputs.plugin_slug }}" ]; then
            mv "plugin-dir/${{ inputs.plugin_slug }}"/* plugin-dir/
            rm -rf "plugin-dir/${{ inputs.plugin_slug }}"
          fi

      # Deploy to WordPress.org SVN
      - name: Deploy to WordPress.org
        if: ${{ inputs.deploy_to_wp }}
        uses: 10up/action-wordpress-plugin-deploy@stable
        env:
          SVN_USERNAME: ${{ secrets.WP_SVN_USERNAME }}
          SVN_PASSWORD: ${{ secrets.WP_SVN_PASSWORD }}
          BUILD_DIR: plugin-dir
          SLUG: ${{ inputs.plugin_slug }}
          VERSION: ${{ inputs.version }}

      - name: Notify Update Feed
        run: |
          curl -X POST ${{ secrets.UPDATE_FEED_URL }} \
            -H "X-API-Key: ${{ secrets.BLD_API_KEY }}" \
            -H "Content-Type: application/json" \
            -d '{"item_updated": "${{inputs.update_feed_item_key}}", "version": "${{ inputs.version }}"}'