name: Check Plugin with PCP
on:
  workflow_call:
    inputs:
        exclude_files:
            description: 'Files to exclude from the check'
            type: string
            required: false
            default: '.gitignore'
        ignore_codes:
            description: 'Ignore codes for the check'
            type: string
            required: false
            default: 'WordPress.DateTime.RestrictedFunctions.date_date'
        plugin_slug:
            description: 'The slug of the plugin on WordPress.org and Freemius'
            required: true
            type: string
        plugin_id:
            description: 'Freemius plugin ID'
            required: true
            type: string
        deploy_to_wp:
            description: 'Wether to deploy to WordPress.org or not'
            type: boolean
            required: true
        fail_on_duplicate:
            description: 'Whether to fail on duplicate plugin versions'
            type: boolean
            required: false
            default: true
        overwrite:
            description: 'Whether to overwrite existing plugin versions'
            type: boolean
            required: false
            default: false
        zip_files:
            description: 'Files and directories to include in the zip'
            type: string
            required: false
            default: 'includes vendor *.php *.txt'
        version:
          description: 'Version to deploy (optional, overrides tag)'
          required: false
          type: string

        update_feed_item_key:
          description: 'The key for the update feed item'
          required: true
          type: string

    secrets:
      BLD_API_KEY:
        required: true
      UPDATE_FEED_URL:
        required: true
      FREEMIUS_PUBLIC_KEY:
        required: true   
      DEV_ID:
        required: true        
      FREEMIUS_SECRET_KEY:
        required: true        
      WP_SVN_USERNAME:
        required: false    
      WP_SVN_PASSWORD:
        required: false
      SSH_PRIVATE_KEY_GRAVITYOPS_CORE:
        required: true
jobs:
    pcp:
        runs-on: ubuntu-latest
        steps:
            # Checkout the repository
            - name: Checkout
              uses: actions/checkout@v4

            # Setup PHP
            - name: Setup PHP
              uses: shivammathur/setup-php@v2
              with:
                  php-version: '8.3'
                  tools: composer

            # Cache Composer Dependencies
            - name: Cache Composer Dependencies
              id: composer-cache
              uses: actions/cache@v3
              with:
                  path: vendor
                  key: composer-${{ hashFiles('composer.json') }}

            - name: Setup SSH Agent
              uses: webfactory/ssh-agent@v0.8.0
              with:
                ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY_GRAVITYOPS_CORE }}

            # Install dependencies if necessary
            - name: Install dependencies
              if: steps.composer-cache.outputs.cache-hit != 'true'
              run: composer install --no-dev --no-progress --optimize-autoloader --no-scripts

            # Run PCP check
            - name: PCP
              uses: wordpress/plugin-check-action@v1
              with:
                  exclude-files: ${{ inputs.exclude_files }}
                  ignore-codes: ${{ inputs.ignore_codes }}

    get_version:
        needs: pcp
        runs-on: ubuntu-latest
        outputs:
            version: ${{ steps.get_version.outputs.version }}
        steps:
            # Checkout the repository
            - name: Checkout
              uses: actions/checkout@v4
              with:
                  fetch-tags: true

            #Get the version from the tag or input
            - name: Get version from tag or input
              id: get_version
              run: |
                  # Prefer manual input if provided
                  INPUT_VERSION="${{ inputs.version }}"
                  if [ -n "$INPUT_VERSION" ]; then
                    VERSION="${INPUT_VERSION#v}"
                    echo "Using manual input version: $VERSION"
                    echo "version=$VERSION" >> "$GITHUB_OUTPUT"
                    exit 0
                  fi
                  
                  # Get the latest tag pointing to HEAD
                  TAG=$(git describe --tags --exact-match 2>/dev/null || echo "")
                  echo "Latest tag on HEAD: $TAG"

                  # If no tag is found, skip deploy
                  if [ -z "$TAG" ]; then
                    echo "No tag on latest commit. Skipping deploy."
                    exit 0
                  fi

                  # Remove leading 'v' from the tag (if present)
                  VERSION=${TAG#v}
                  echo "Stripped version: $VERSION"

                  # Set output using the GITHUB_OUTPUT file
                  echo "version=$VERSION" >> $GITHUB_OUTPUT


    maybe_deploy:
        needs: get_version
        if: ${{ needs.get_version.outputs.version && needs.get_version.outputs.version != '' }}
        uses: eitan-brightleaf/.github/.github/workflows/deploy-plugin.yml@main
        with:
          plugin_slug: ${{ inputs.plugin_slug }}
          plugin_id: ${{ inputs.plugin_id }}
          deploy_to_wp: ${{ inputs.deploy_to_wp }}
          fail_on_duplicate: ${{ inputs.fail_on_duplicate }}
          overwrite: ${{ inputs.overwrite }}
          version: ${{ needs.get_version.outputs.version }}
          zip_files: ${{ inputs.zip_files }}
          update_feed_item_key: ${{ inputs.update_feed_item_key }}
        secrets:
          BLD_API_KEY: ${{ secrets.BLD_API_KEY }}
          UPDATE_FEED_URL: ${{ secrets.UPDATE_FEED_URL }}
          FREEMIUS_PUBLIC_KEY: ${{ secrets.FREEMIUS_PUBLIC_KEY }}
          DEV_ID: ${{ secrets.DEV_ID }}
          FREEMIUS_SECRET_KEY: ${{ secrets.FREEMIUS_SECRET_KEY }}
          WP_SVN_USERNAME: ${{ secrets.WP_SVN_USERNAME }}
          WP_SVN_PASSWORD: ${{ secrets.WP_SVN_PASSWORD }}
          SSH_PRIVATE_KEY_GRAVITYOPS_CORE: ${{ secrets.SSH_PRIVATE_KEY_GRAVITYOPS_CORE }}
